{"address": 
    {"city": "Glen Mills", 
        "community": null, 
        "neighborhood": null, 
        "state": "PA",
         "streetAddress": "88 Locksley Rd", 
         "subdivision": "None Available", 
         "zipcode": "19342"}, 
         "annualHomeownersInsurance": 3230, 
         "attributionInfo": {"agentEmail": null, 
            "agentLicenseNumber": null, 
            "agentName": "Samantha Johannessen", 
            "agentPhoneNumber": "267-800-8806", 
            "attributionTitle": null, 
            "brokerName": "Tesla Realty Group, LLC", 
            "brokerPhoneNumber": "8448375274", 
            "buyerAgentMemberStateLicense": null, 
            "buyerAgentName": null, 
            "buyerBrokerageName": null, 
            "coAgentLicenseNumber": null, 
            "coAgentName": null, 
            "coAgentNumber": null, 
            "infoString10": "The data relating to real estate for sale on this website appears in part through the BRIGHT Internet Data Exchange program, a voluntary cooperative exchange of property listing data between licensed real estate brokerage firms, and is provided by BRIGHT through a licensing agreement.Listing information is from various brokers who participate in the Bright MLS IDX program and not all listings may be visible on the site. The property information being provided on or through the website is for the personal, non-commercial use of consumers and such information may not be used for any purpose other than to identify prospective properties consumers may be interested in purchasing.Some properties which appear for sale on the website may no longer be available because they are for instance, under contract, sold or are no longer being offered for sale.Property information displayed is deemed reliable but is not guaranteed. Copyright 2025 Bright MLS, Inc. [Click here for more information](/mls-disclaimers/#5632)", 
            "infoString16": null, 
            "infoString3": "https://photos.zillowstatic.com/fp/3c0b241c63af930483095615f244c283-zillow_web_95_35.jpg", 
            "infoString5": "267-800-8806", 
            "lastChecked": "2025-03-18 17:29:38", 
            "lastUpdated": "2025-03-05 02:38:56", 
            "listingAgentAttributionContact": null, 
            "listingAgents": [[Object]], 
            "listingAgreement": "Exclusive Right To Sell", "listingAttributionContact": null, 
            "listingOffices": [[Object]], 
            "mlsDisclaimer": "The data relating to real estate for sale on this website appears in part through the BRIGHT Internet Data Exchange program, a voluntary cooperative exchange of property listing data between licensed real estate brokerage firms, and is provided by BRIGHT through a licensing agreement.Listing information is from various brokers who participate in the Bright MLS IDX program and not all listings may be visible on the site. The property information being provided on or through the website is for the personal, non-commercial use of consumers and such information may not be used for any purpose other than to identify prospective properties consumers may be interested in purchasing.Some properties which appear for sale on the website may no longer be available because they are for instance, under contract, sold or are no longer being offered for sale. Property information displayed is deemed reliable but is not guaranteed. Copyright 2025 Bright MLS, Inc. [Click here for more information](/mls-disclaimers/#5632)", 
            "mlsId": "PADE2081336", 
            "mlsName": "Bright MLS", 
            "providerLogo": "https://photos.zillowstatic.com/fp/3c0b241c63af930483095615f244c283-zillow_web_95_35.jpg", 
            "trueStatus": null}, 
            "bathrooms": 4, 
            "bedrooms": 4, 
            "brokerId": null, 
            "brokerageName": "Tesla Realty Group, LLC", 
            "building": null, 
            "buildingId": null, 
            "buildingPermits": null, 
            "city": "Glen Mills", 
            "cityId": 18295, 
            "climate": {
                "airSources": 
                {"primary": [Object]}, 
                "fireSources": 
                {"primary": [Object]}, 
                "floodSources": 
                {"primary": [Object]}, 
                "heatSources": 
                {"primary": [Object]}, 
                "windSources": {"primary": [Object]}}, 
                "comingSoonOnMarketDate": null, "contact_recipients": [{"agent_reason": 1, 
                    "badge_type": "Premier Agent", 
                    "business_name": "Zillow Group", 
                    "display_name": "Premier Broker Flex Atlanta GA", 
                    "image_url": "https://www.zillowstatic.com/static/images/nophoto_h_g.png", 
                    "phone": [Object], 
                    "rating_average": 0, 
                    "recent_sales": 0, 
                    "review_count": 0, 
                    "zpro": null, 
                    "zuid": "X1-ZUv2ktj4jt3nyh_98wrm"}], 
                    "contingentListingType": null, 
                    "country": "USA", 
                    "county": "Delaware County", 
                    "countyFIPS": "42045", 
                    "countyId": 2251, 
                    "currency": "USD", 
                    "datePosted": "2024-12-27", 
                    "dateSold": null, 
                    "description": "Charming updated Glen Mills home.  This home is located in the heart of Glen Mills, in the highly sought after West Chester Area School District, has convenient access to Philadelphia, the WAWA Septa Train Station, the Commodore Barry Bridge to NJ, and Delaware.   It is nestled within trees, offering superb privacy, and close proximity to parks and outdoor activities.    This remodeled home provides plenty of charm with modern amenities.   Some features were restored to their original beauty, such as the original stair case that was restored by a master carpenter.  While other areas were completely remodeled to include:  An open floor plan A gourmet, eat-in kitchen with custom cabinets and granite. An updated dining room with wainscoting and a crystal chandelier. A breakfast nook with built-in benches and storage. A mud room with laundry, powder room, and dry bar. A Primary Bedroom with sitting area and balcony. A Primary Bathroom with bidet, double sinks, and custom tile shower. An additional custom bathroom with double sinks. An Au pair suite with kitchenette and a full bathroom. A partially finished basement with ample space for a home gym, a music room, a game room, and/or a second living room.  The home was completely renovated in 2017, with new electric, HVAC, and plumbing, and has a whole home water softener and filtration system.", 
                    "favoriteCount": 138, 
                    "homeFacts": null, 
                    "homeInsights": 
                    [{"insights": [Array]}], 
                    "homeStatus": "FOR_SALE", 
                    "homeType": "SINGLE_FAMILY", 
                    "imgSrc": "https://photos.zillowstatic.com/fp/9f6402680f29322b2055f80f472f2d89-p_d.jpg", 
                    "isListedByOwner": null, 
                    "isShowcaseListing": false, 
                    "latitude": 39.93016, 
                    "listed_by": {
                        "agent_reason": 3, 
                        "badge_type": "Listing Agent", 
                        "business_name": "Tesla Realty Group, LLC", 
                        "display_name": "Samantha Johannessen", 
                        "image_url": "https://www.zillowstatic.com/static/images/nophoto_h_n.png", 
                        "phone": "", 
                        "profile_url": "https://www.zillow.com/profile/zuser20180503083507854/", 
                        "rating_average": 0, 
                        "recent_sales": 0,
                        "review_count": 0, 
                        "zpro": false, 
                        "zuid": "X1-ZUvlvtez6cck5l_2xcn4"
                    }, 
                    "listingProvider": null, 
                    "listingSubType": {
                        "is_FSBA": true, 
                        "is_FSBO": false, 
                        "is_bankOwned": false, 
                        "is_comingSoon": false, 
                        "is_forAuction": false, 
                        "is_foreclosure": false, 
                        "is_newHome": false, 
                        "is_pending": false}, 
                        "livingArea": 3136, 
                        "livingAreaUnits": "sqft", 
                        "livingAreaValue": 3136, 
                        "longitude": -75.50621, 
                        "mlsid": "PADE2081336", 
                        "monthlyHoaFee": null, 
                        "mortgageRates": null, 
                        "mortgageZHLRates": 
                        {"arm5Bucket": 
                            {"lastUpdated": 1742344963451, 
                            "rate": 6.162, 
                            "rateSource": "ZGMI"}, 
                            "fifteenYearFixedBucket": 
                                {"lastUpdated": 1742344963451, 
                                "rate": 5.916, 
                                "rateSource": "ZGMI"}, 
                                "thirtyYearFixedBucket": {
                                "lastUpdated": 1742344963451, 
                                "rate": 6.542, 
                                "rateSource": "ZGMI"}}, 
                                "nearbyHomes": [{
                                "address": [Object], 
                                "currency": "USD", 
                                "homeStatus": "OTHER", 
                                "homeType": "SINGLE_FAMILY", 
                                "latitude": 39.931633, 
                                "livingArea": null, 
                                "livingAreaUnits": null,
                                "livingAreaUnitsShort": null, 
                                "livingAreaValue": null, 
                                "longitude": -75.50648, 
                                "lotAreaUnits": "Acres", 
                                "lotAreaValue": 1, 
                                "lotSize": 43560, 
                                "miniCardPhotos": [Array], 
                                "price": 633100, 
                                "zpid": 301933659}, 
                                {"address": [Object], 
                                "currency": "USD", 
                                "homeStatus": "OTHER", 
                                "homeType": "SINGLE_FAMILY", 
                                "latitude": 39.932106,
                                "livingArea": 1582, 
                                 "livingAreaUnits": "Square Feet", "livingAreaUnitsShort": "sqft", 
                                 "livingAreaValue": 1582, 
                                "longitude": -75.50517, "lotAreaUnits": "Acres", "lotAreaValue": 1.7599862258953, "lotSize": 76665, 
                                 "miniCardPhotos": [Array], 
                                "price": 466800, 
                                "zpid": 9454862}, 
                                {"address": [Object], 
                                "currency": "USD", 
                                "homeStatus": "OTHER", 
                                 "homeType": "SINGLE_FAMILY", 
                                 "latitude": 39.93237, 
                                 "livingArea": 2626, 
                                 "livingAreaUnits": 
                                 "Square Feet", 
                                 "livingAreaUnitsShort": "sqft", 
                                 "livingAreaValue": 2626, 
                                 "longitude": -75.50638, 
                                 "lotAreaUnits": "Acres", 
                                 "lotAreaValue": 2.6859963269054, 
                                 "lotSize": 117002, 
                                 "miniCardPhotos": [Array], 
                                 "price": 706300, 
                                 "zpid": 9454864}, 
                                 {"address": [Object], 
                                "currency": "USD", 
                                "homeStatus": "OTHER", 
                                "homeType": "SINGLE_FAMILY", 
                                "latitude": 39.9308, "livingArea": null, "livingAreaUnits": null, 
                                "livingAreaUnitsShort": null, 
                                "livingAreaValue": null, 
                                "longitude": -75.50324, 
                                "lotAreaUnits": "Acres", 
                                "lotAreaValue": 18.275987144169, 
                                "lotSize": 796102, 
                                "miniCardPhotos": [Array], 
                                "price": 833700, 
                                "zpid": 301933658}, 
                                {"address": [Object], 
                                "currency": "USD", 
                                "homeStatus": "OTHER", 
                                "homeType": "SINGLE_FAMILY", 
                                "latitude": 39.932728, 
                                "livingArea": 2836, 
                                "livingAreaUnits": "Square Feet", "livingAreaUnitsShort": "sqft", 
                                "livingAreaValue": 2836, 
                                "longitude": -75.50528, 
                                "lotAreaUnits": "Acres", 
                                "lotAreaValue": 2.0399908172635, 
                                "lotSize": 88861, 
                                "miniCardPhotos": [Array], 
                                "price": 641700, 
                                "zpid": 9455267}, 
                                {"address": [Object], 
                                 "currency": "USD", 
                                "homeStatus": "OTHER", 
                                "homeType": "SINGLE_FAMILY", 
                                "latitude": 39.92802, 
                                "livingArea": 1756, 
                                "livingAreaUnits": "Square Feet", "livingAreaUnitsShort": "sqft", 
                                "livingAreaValue": 1756, 
                                "longitude": -75.50839, 
                                "lotAreaUnits": "Acres", 
                                "lotAreaValue": 4.577984389348, 
                                "lotSize": 199417, 
                                "miniCardPhotos": [Array], 
                                "price": 610000, 
                                "zpid": 9455264}, 
                                {"address": [Object], 
                                "currency": "USD", 
                                "homeStatus": "OTHER", 
                                "homeType": "SINGLE_FAMILY", 
                                "latitude": 39.928356, 
                                "livingArea": 4950, 
                                "livingAreaUnits": "Square Feet", "livingAreaUnitsShort": "sqft", 
                                "livingAreaValue": 4950, 
                                "longitude": -75.50356, 
                                "lotAreaUnits": "Acres", 
                                "lotAreaValue": 49, 
                                "lotSize": 2134440, 
                                "miniCardPhotos": [Array], 
                                "price": 1228100, "zpid": 54525247}, 
                                {"address": [Object], 
                                "currency": "USD", 
                                "homeStatus": "OTHER", 
                                "homeType": "SINGLE_FAMILY", 
                                "latitude": 39.932804, 
                                "livingArea": 2416, 
                                "livingAreaUnits": "Square Feet", "livingAreaUnitsShort": "sqft", 
                                "livingAreaValue": 2416, 
                                "longitude": -75.50705, 
                                "lotAreaUnits": "Acres", 
                                "lotAreaValue": 2, 
                                "lotSize": 87120, 
                                "miniCardPhotos": [Array], 
                                "price": 717400, 
                                "zpid": 9454865}], 
                                "neighborhoodMapThumb": 
                                [
                                {"url": "https://photos.zillowstatic.com/fp/9f6402680f29322b2055f80f472f2d89-p_c.jpg"}], "neighborhoodRegion": null, 
                                "openHouseSchedule": {}, 
                                "pageViewCount": 3247,
                                 "photoCount": 48, 
                                 "price": 769000, 
                                 "priceChange": -56000, 
                                 "priceChangeDate": 1741132800000, "priceChangeDateString": "2025-03-05", "priceHistory": 
                                 [{"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2025-03-05", 
                                "event": "Price change", 
                                "postingIsRental": false, 
                                "price": 769000, 
                                "priceChangeRate": -0.067878787878788, "pricePerSquareFoot": 245, 
                                "sellerAgent": null, 
                                "showCountyLink": false, 
                                "source": "Bright MLS", 
                                "time": 1741132800000}, 
                                {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2025-02-12", 
                                "event": "Price change", 
                                "postingIsRental": false, 
                                "price": 825000, 
                                "priceChangeRate": -0.028840494408476, "pricePerSquareFoot": 263, 
                                "sellerAgent": null, 
                                "showCountyLink": false, 
                                "source": "Bright MLS", 
                                "time": 1739318400000}, 
                                {"attributeSource": [Object],
                                 "buyerAgent": null, 
                                 "date": "2024-12-27", 
                                 "event": "Listed for sale", 
                                 "postingIsRental": false, 
                                 "price": 849500, 
                                 "priceChangeRate": 0.46718480138169, "pricePerSquareFoot": 271, 
                                 "sellerAgent": null, 
                                 "showCountyLink": false, 
                                 "source": "Bright MLS", 
                                 "time": 1735257600000}, 
                                 {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2018-09-13", 
                                "event": "Listing removed", 
                                "postingIsRental": false, 
                                "price": 579000, 
                                "priceChangeRate": 0, 
                                "pricePerSquareFoot": 185, 
                                "sellerAgent": null,
                                "showCountyLink": false, 
                                "source": "BHHS Fox & Roach - West Chester", 
                                "time": 1536796800000}, 
                                {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2018-08-26", 
                                "event": "Listing removed", 
                                "postingIsRental": true, 
                                "price": 3000, 
                                "priceChangeRate": 0, 
                                "pricePerSquareFoot": 1, 
                                "sellerAgent": null, 
                                "showCountyLink": false, 
                                "source": "BHHS Fox & Roach-West Chester", 
                                "time": 1535241600000}, 
                                {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2018-08-06", 
                                "event": "Price change", 
                                "postingIsRental": false, 
                                "price": 579000, 
                                "priceChangeRate": -0.03338898163606, "pricePerSquareFoot": 185, 
                                "sellerAgent": null, "showCountyLink": false, "source": "BHHS Fox & Roach - West Chester", 
                                "time": 1533513600000}, 
                                {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2018-07-28", 
                                "event": "Listed for rent", 
                                "postingIsRental": true, 
                                "price": 3000, 
                                "priceChangeRate": 0, 
                                "pricePerSquareFoot": 1, 
                                "sellerAgent": null, 
                                "showCountyLink": false, 
                                "source": "BHHS Fox & Roach-West Chester", 
                                "time": 1532736000000}, 
                                {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2018-07-12", 
                                "event": "Price change", 
                                "postingIsRental": false, 
                                "price": 599000, 
                                "priceChangeRate": -0.0416, 
                                "pricePerSquareFoot": 191, 
                                "sellerAgent": null,
                                 "showCountyLink": false, 
                                 "source": "BHHS Fox & Roach - West Chester", 
                                 "time": 1531353600000}, 
                                 {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2018-06-22", 
                                "event": "Listed for sale", 
                                "postingIsRental": false, 
                                "price": 625000, 
                                "priceChangeRate": 2.0637254901961, "pricePerSquareFoot": 199, 
                                "sellerAgent": null, 
                                "showCountyLink": false, 
                                "source": "BHHS Fox & Roach-West Chester", 
                                "time": 1529625600000}, 
                                {"attributeSource": [Object], 
                                "buyerAgent": null,
                                "date": "2016-08-18", 
                                "event": "Sold", 
                                "postingIsRental": false, 
                                "price": 204000, 
                                "priceChangeRate": -0.036372224846481, "pricePerSquareFoot": 65, 
                                "sellerAgent": null, 
                                "showCountyLink": false, 
                                "source": "Public Record", 
                                "time": 1471478400000}, 
                                {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2016-04-12", 
                                "event": "Listing removed", 
                                "postingIsRental": false, 
                                "price": 211700, "priceChangeRate": 0, "pricePerSquareFoot": 68, 
                                "sellerAgent": null, 
                                "showCountyLink": false, 
                                "source": "REALHome Services and Solutions", "time": 1460419200000}, 
                                {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2016-03-01", 
                                "event": "Price change", 
                                "postingIsRental": false, 
                                "price": 211700, 
                                "priceChangeRate": -0.049820466786355, "pricePerSquareFoot": 68, 
                                "sellerAgent": null, 
                                "showCountyLink": false, 
                                "source": "REALHome Services and Solutions", 
                                "time": 1456790400000}, 
                                {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2016-01-29", 
                                "event": "Price change", 
                                "postingIsRental": false, 
                                "price": 222800, 
                                "priceChangeRate": -0.049893390191898, "pricePerSquareFoot": 71, 
                                "sellerAgent": null, 
                                "showCountyLink": false, 
                                "source": "REALHome Services and Solutions", 
                                "time": 1454025600000}, 
                                {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2015-12-31", 
                                "event": "Price change", 
                                "postingIsRental": false, 
                                "price": 234500, 
                                "priceChangeRate": -0.049837925445705, "pricePerSquareFoot": 75, 
                                "sellerAgent": null, 
                                "showCountyLink": false, 
                                "source": "REALHome Services and Solutions", 
                                "time": 1451520000000}, 
                                {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2015-12-02",
                                "event": "Price change", 
                                "postingIsRental": false, 
                                "price": 246800, 
                                "priceChangeRate": -0.049672699268387, "pricePerSquareFoot": 79, 
                                "sellerAgent": null, 
                                "showCountyLink": false, 
                                "source": "REALHome Services and Solutions", 
                                "time": 1449014400000}, 
                                {"attributeSource": [Object], 
                                "buyerAgent": null, 
                                "date": "2015-11-03", 
                                "event": "Listed for sale", 
                                "postingIsRental": false, 
                                "price": 259700, 
                                "priceChangeRate": 0, 
                                "pricePerSquareFoot": 83, 
                                "sellerAgent": null, 
                                "showCountyLink": false, 
                                "source": "REALHome Services and Solutions", 
                                "time": 1446508800000}], 
                                "propertyTaxRate": 1.67, 
                                "propertyTypeDimension": "Single Family", "providerListingID": null, 
                                "rentZestimate": null, 
                                "resoFacts": 
                                {"aboveGradeFinishedArea": "2,494", "accessibilityFeatures": ["2+ Access Exits", "Doors - Swing In", "Accessible Doors", "Accessible Hallway(s)"], 
                                "additionalFeeInfo": null, "additionalParcelsDescription": null, 
                                "appliances": ["Cooktop", "Built-In Microwave", "Dishwasher", "Oven - Wall", "Other Water Heater"], "architecturalStyle": "Cape Cod", "associationAmenities": null, 
                                "associationFee": null, 
                                "associationFee2": null, 
                                "associationFeeIncludes": null, 
                                "associationName": null, 
                                "associationName2": null, 
                                "associationPhone": null, 
                                "associationPhone2": null, 
                                "associations": {}, 
                                "atAGlanceFacts": [[Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object]], 
                                "attic": null, "availabilityDate": null,
                                "basement": "Partially Finished", 
                                "basementYN": true, 
                                "bathrooms": 4, 
                                "bathroomsFloat": 4, 
                                "bathroomsFull": 3, 
                                "bathroomsHalf": 1, 
                                "bathroomsOneQuarter": null, 
                                "bathroomsPartial": null, 
                                "bathroomsThreeQuarter": null, 
                                "bedrooms": 4, 
                                "belowGradeFinishedArea": "642", 
                                "bodyType": null, 
                                "builderModel": null, 
                                "builderName": null, 
                                "buildingArea": null, 
                                "buildingAreaSource": null, 
                                "buildingFeatures": null, 
                                "buildingName": null, 
                                "canRaiseHorses": false, 
                                "carportParkingCapacity": null, 
                                "cityRegion": "Glen Mills", 
                                "commonWalls": null, 
                                "communityFeatures": null, 
                                "compensationBasedOn": null, 
                                "constructionMaterials": ["Frame"], 
                                "contingency": null, 
                                "cooling": ["Central A/C", "Electric"], "coveredParkingCapacity": 1, 
                                "cropsIncludedYN": null, 
                                "cumulativeDaysOnMarket": null, 
                                "daysOnZillow": 81, 
                                "developmentStatus": null, 
                                "doorFeatures": null, 
                                "electric": ["200+ Amp Service"], 
                                "elementarySchool": "Penn Wood", "elementarySchoolDistrict": "West Chester Area", "elevation": null, 
                                "elevationUnits": null, 
                                "entryLevel": null, 
                                "entryLocation": null, 
                                "exclusions": ["Staging Items"], 
                                "exteriorFeatures": ["Lighting", "Rain Gutters", "Stone Retaining Walls", "Extensive Hardscape", "Balcony"], 
                                "feesAndDues": {}, 
                                "fencing": null, 
                                "fireplaceFeatures": ["Gas/Propane"], 
                                "fireplaces": 1, 
                                "flooring": ["Hardwood", "Ceramic Tile", "Carpet"], 
                                "foundationArea": null, 
                                "foundationDetails": ["Block", "Basement"], "frontageLength": null, 
                                "frontageType": null, 
                                "furnished": false, 
                                "garageParkingCapacity": 1, 
                                "gas": null, 
                                "greenBuildingVerificationType": null, "greenEnergyEfficient": null, 
                                "greenEnergyGeneration": null, "greenIndoorAirQuality": null, 
                                "greenSustainability": null, 
                                "greenWaterConservation": null, "hasAdditionalParcels": false, 
                                "hasAssociation": false, 
                                "hasAttachedGarage": true, 
                                "hasAttachedProperty": false, 
                                "hasCarport": false, 
                                "hasCooling": true, 
                                "hasElectricOnProperty": null, 
                                "hasFireplace": true, 
                                "hasGarage": true, 
                                "hasHeating": true, 
                                "hasHomeWarranty": false, 
                                "hasLandLease": false, 
                                "hasOpenParking": true, 
                                "hasPetsAllowed": null, 
                                "hasPrivatePool": null, 
                                "hasRentControl": null, 
                                "hasSpa": false, 
                                "hasView": true, 
                                "hasWaterfrontView": null, 
                                "heating": ["Central", "Heat Pump - Electric BackUp", "Electric", "Propane - Leased"], 
                                "highSchool": "West Chester Bayard Rustin", "highSchoolDistrict": "West Chester Area", 
                                "hoaFee": null, 
                                "hoaFeeTotal": null, 
                                "homeType": "SingleFamily", 
                                "horseAmenities": null, 
                                "horseYN": false, 
                                "inclusions": ["Refrigerator In Kitchen.  Refrigerator In Aupair Suite."], 
                                "incomeIncludes": null, 
                                "interiorFeatures": ["9'+ Ceilings"], "irrigationWaterRightsAcres": null, "irrigationWaterRightsYN": null, 
                                "isNewConstruction": false, 
                                "isSeniorCommunity": null, 
                                "landLeaseAmount": null, 
                                "landLeaseExpirationDate": null, 
                                "laundryFeatures": ["Main Level"], 
                                "leaseTerm": null, 
                                "levels": "Four", 
                                "listAOR": null, 
                                "listingId": null, 
                                "listingTerms": "Conventional,Cash,FHA,VA Loan", "livingArea": "3,136 sqft", 
                                "livingAreaRange": null, 
                                "livingAreaRangeUnits": null, 
                                "livingQuarters": {}, 
                                "lotFeatures": null, 
                                "lotSize": "0.81 Acres", 
                                "lotSizeDimensions": null, 
                                "mainLevelBathrooms": 1, 
                                "mainLevelBedrooms": 0, 
                                "marketingType": null, 
                                "media": {}, 
                                "middleOrJuniorSchool": "Stetson", "middleOrJuniorSchoolDistrict": "West Chester Area", "municipality": "THORNBURY TWP", "numberOfUnitsInCommunity": null, "numberOfUnitsVacant": null, 
                                "offerReviewDate": null, 
                                "onMarketDate": 1735257600000, 
                                "openParkingCapacity": 5, 
                                "otherEquipment": null, 
                                "otherFacts": {}, 
                                "otherParking": null, 
                                "otherStructures": ["Above Grade", "Below Grade"], "ownership": "Fee Simple", "ownershipType": null, "parcelNumber": "44000021100", 
                                "parkName": null, 
                                "parkingCapacity": 6, 
                                "parkingFeatures": ["Garage Faces Side", "Asphalt Driveway", "Attached Garage", "Driveway"], "patioAndPorchFeatures": ["Patio", "Porch", "Deck"], "petsMaxWeight": null, 
                                "poolFeatures": ["None"], 
                                "pricePerSquareFoot": 245, 
                                "propertyCondition": "Very Good", 
                                "propertySubType": ["Single Family Residence"], "roadSurfaceType": null, 
                                "roofType": "Architectural Shingle", 
                                "roomTypes": ["Dining Room", "Primary Bedroom", "Bedroom 2", "Bedroom 3", "Kitchen", "Family Room", "Breakfast Room", "In-Law/auPair/Suite", "Office", "Bathroom 2", "Primary Bathroom"], 
                                "rooms": [[Object]], 
                                "securityFeatures": ["Carbon Monoxide Detector(s)", "Smoke Detector(s)"], 
                                "sewer": ["On Site Septic"], 
                                "spaFeatures": null, 
                                "specialListingConditions": "Standard", 
                                "stories": 4, 
                                "storiesDecimal": 4, 
                                "storiesTotal": 4, 
                                "structureType": "Detached", 
                                "subdivisionName": "None Available", "taxAnnualAmount": 8345, 
                                "taxAssessedValue": 559500, 
                                "tenantPays": null, 
                                "topography": null, 
                                "totalActualRent": null, 
                                "utilities": ["Electricity Available", "Propane", "Fiber Optic", "Cable"], 
                                "vegetation": null, 
                                "view": ["Trees/Woods"], 
                                "virtualTour": null, 
                                "waterBodyName": null, 
                                "waterSource": ["Well"], 
                                "waterView": null, 
                                "waterViewYN": false, 
                                "waterfrontFeatures": null, 
                                "windowFeatures": null, 
                                "woodedArea": null, 
                                "yearBuilt": 1935, 
                                "yearBuiltEffective": 2017, 
                                "zoning": "R-1", 
                                "zoningDescription": null}, 
                                "schools": [{"assigned": null, 
                                "distance": 1.9, 
                                "grades": "K-5", 
                                "isAssigned": null, 
                                "level": "Elementary", 
                                "link": "https://www.greatschools.org/pennsylvania/west-chester/2966-Penn-Wood-El-School/", 
                                "name": "Penn Wood El School", 
                                "rating": 7, 
                                "size": null, 
                                "studentsPerTeacher": null, 
                                "totalCount": null, 
                                "type": "Public"}, 
                                {"assigned": null, 
                                "distance": 4.4, 
                                "grades": "6-8", 
                                "isAssigned": null, 
                                "level": "Middle", 
                                "link": "https://www.greatschools.org/pennsylvania/west-chester/2958-Stetson-Middle-School/", 
                                "name": "Stetson Middle School", 
                                "rating": 6, 
                                "size": null, 
                                "studentsPerTeacher": null, 
                                "totalCount": null, 
                                "type": "Public"}, 
                                {"assigned": null, 
                                "distance": 2.6, 
                                "grades": "9-12",
                                "isAssigned": null, 
                                "level": "High", 
                                "link": "https://www.greatschools.org/pennsylvania/west-chester/6473-West-Chester-Bayard-Rustin-High-School/", 
                                "name": "West Chester Bayard Rustin High School", "rating": 7, "size": null, 
                                "studentsPerTeacher": null, 
                                "totalCount": null, 
                                "type": "Public"}], 
                                "solarPotential": null, 
                                "state": "PA", 
                                "stateId": 47, 
                                "streetAddress": "88 Locksley Rd", 
                                "taxHistory": [{"taxIncreaseRate": 0.012224676, "taxPaid": 7324.64, 
                                "time": 1710808963434, 
                                "value": 559500, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0.03339013, 
                                "taxPaid": 7236.18, 
                                "time": 1679186563434, 
                                "value": 559500, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0, 
                                "taxPaid": 7002.37, 
                                "time": 1647650563434, 
                                "value": 559500, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 5.377154, 
                                "taxPaid": 7002.37, 
                                "time": 1616114563434, 
                                "value": 559500, 
                                "valueIncreaseRate": 1.782613}, 
                                {"taxIncreaseRate": -0.746438, 
                                "taxPaid": 1098.04, 
                                "time": 1584578563434, 
                                "value": 201070, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0.034809373, 
                                "taxPaid": 4330.46, 
                                "time": 1552956163434, 
                                "value": 201070, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 3.6928365, 
                                "taxPaid": 4184.79, 
                                "time": 1521420163434, 
                                "value": 201070, 
                                "valueIncreaseRate": 0.23742999}, 
                                {"taxIncreaseRate": 0, 
                                "taxPaid": 891.74, 
                                "time": 1489884163434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0, 
                                "taxPaid": 891.74, 
                                "time": 1458348163434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0, 
                                "taxPaid": 891.74, 
                                "time": 1426725763434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0.027527817, 
                                "taxPaid": 891.74, 
                                "time": 1395189763434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0.028306972, 
                                "taxPaid": 867.85, 
                                "time": 1363653763434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0.0026969782, 
                                "taxPaid": 843.96, 
                                "time": 1332117763434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0.020415867, 
                                "taxPaid": 841.69, 
                                "time": 1300495363434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0.07468104, 
                                "taxPaid": 824.85, 
                                "time": 1268959363434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0, 
                                "taxPaid": 767.53, 
                                "time": 1237423363434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0.08314876, 
                                "taxPaid": 767.53, 
                                "time": 1205887363434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0, 
                                "taxPaid": 708.61, 
                                "time": 1174264963434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0, 
                                "taxPaid": 708.61,
                                "time": 1142732563434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": -0.02001166, 
                                "taxPaid": 708.61, 
                                "time": 1111196563434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0.08537977, 
                                "taxPaid": 723.08, 
                                "time": 1079660563434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0.07893627, 
                                "taxPaid": 666.2, 
                                "time": 1048038163434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0, 
                                "taxPaid": 617.46, 
                                "time": 1016502163434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}, 
                                {"taxIncreaseRate": 0, 
                                "taxPaid": 617.46, 
                                "time": 953430163434, 
                                "value": 162490, 
                                "valueIncreaseRate": 0}], 
                                "timeOnZillow": "81 days", 
                                "timeZone": "America/New_York", 
                                "url": "/homedetails/88-Locksley-Rd-Glen-Mills-PA-19342/9455266_zpid/", "yearBuilt": 1935, 
                                "zestimate": null, 
                                "zestimateHighPercent": null, 
                                "zestimateLowPercent": null, 
                                "zipcode": "19342", 
                                "zpid": 9455266}
